site_name: RISC-V Steel Docs
site_author: Rafael Calcada
site_description: RISC-V Steel is a free and open collection of RISC-V IP aimed to speed up building new RISC-V systems from scratch.
repo_url: https://github.com/riscv-steel/riscv-steel
edit_uri: edit/main/docs/source/
markdown_extensions:
    - abbr
    - attr_list
    - md_in_html
    - tables
    - footnotes
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
theme: 
    icon:
        annotation: material/plus-circle
        logo: bootstrap/cpu
        favicon: bootstrap/cpu
    name: material
    custom_dir: overrides
    highlightjs: true
    palette: 
        primary: indigo
    features:
        - navigation.top
        - navigation.tabs
        - toc.integrate
        - navigation.instant
        - navigation.instant.progress
        - navigation.sections
        - content.code.copy
        - content.code.select
extra:
    analytics:
        provider: google
        property: G-6380GKCWC3
extra_css: [extra.css]
plugins:
    - search
docs_dir: source/
copyright: Copyright &copy; Rafael Calcada
nav:
    - Homepage: 'index.md'
    - Getting Started: 'getting-started.md'
    - SoC Reference: 'soc-reference.md'
    - Core Reference: 'core-reference.md'        
    - Steel API: 'steel-api.md'
    - Software Guide: 'software-guide.md'
    - License: 'license.md'