site_name: RISC-V Steel
site_author: Rafael Calcada
site_description: RISC-V Steel is a free collection of RISC-V IP cores aimed to speed up building new RISC-V systems from scratch.
repo_url: https://github.com/riscv-steel/riscv-steel
edit_uri: edit/main/docs/source/
markdown_extensions:
    - attr_list
    - md_in_html
    - tables
    - footnotes
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
theme: 
    icon:
        annotation: material/plus-circle
        logo: bootstrap/cpu
        favicon: bootstrap/cpu
    name: material
    custom_dir: overrides
    highlightjs: true
    palette: 
        - scheme: default
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
    features:
        - navigation.tabs
        - toc.integrate
        - content.code.copy
        - content.code.select
extra:
    analytics:
        provider: google
        property: G-6380GKCWC3
extra_css: [extra.css]
plugins:
    - search
docs_dir: source/
copyright: Copyright &copy; Rafael Calcada
nav:
    - Home: 'index.md'
    - Getting Started: 'getting-started.md'
    #- Reference Guide: 'reference-guide.md'
    #  - Microarchitecture: 'microarchitecture.md'
    #  - Interfaces: 'interfaces.md'
    #  - Timing diagrams: 'timing.md'
    #  - Trap handling: 'traps.md'
    #- Hello World example: 'hello-world.md'
    - License: 'license.md'